const ALL_BOOKS = [
  {
    title: 'Big Magic',
    author: 'Elizabeth Gilbert',
    year: '2014',
    status: 'available',
    rating: 4,
    likes: 234,
    views: 444,
    genres: 'motivational',
    labels: 'Self-help',
    timeAdded: 312,
    imageURL: 'https://bit.ly/3cRWHo1'
  },
  {
    title: 'Effective Python',
    author: 'Diomidis Spinellis',
    year: '2017',
    status: 'available',
    rating: 4,
    likes: 334,
    views: 944,
    genres: 'motivational',
    labels: 'Creative',
    timeAdded: 321,
    imageURL: 'https://bit.ly/3e2hN4g'
  },
  {
    title: 'Built To Last',
    author: 'Jim Collins, Jerry I. Porras',
    year: '2001',
    status: 'Borrowed Out',
    rating: 4,
    likes: 434,
    views: 144,
    genres: 'Business, Entrepreneurship',
    labels: 'Fianace',
    timeAdded: 332,
    imageURL: 'https://bit.ly/2UuKC1O'
  },
  {
    title: 'The Lean Startup',
    author: 'Eric Reis - 2005',
    year: '2001',
    status: 'available',
    rating: 4,
    likes: 43,
    views: 14,
    genres: 'motivational',
    labels: 'Enterperneurship',
    timeAdded: 342,
    imageURL: 'https://bit.ly/2Yku3Xr'
  },
  {
    title: 'The Effective Engineer',
    author: 'Edmond Lau',
    year: '2009',
    status: 'available',
    rating: 4,
    likes: 433,
    views: 104,
    genres: 'Motivational',
    labels: 'Manufacturing',
    timeAdded: 332,
    imageURL: 'https://bit.ly/37jzPgb'
  },
  {
    title: 'The Calculating Stars',
    author: 'Cady Coleman',
    year: '2019',
    status: 'available',
    rating: 4,
    likes: 433,
    views: 104,
    genres: 'Scifi',
    labels: 'Innovation',
    timeAdded: 92,
    imageURL: 'https://bit.ly/2XNxKpm'
  },
  {
    title: 'The Silent Patient',
    author: 'Alex Michealidies',
    year: '2019',
    status: 'Borrowed out',
    rating: 4,
    likes: 433,
    views: 104,
    genres: 'Scifi',
    labels: 'Meditation',
    timeAdded: 62,
    imageURL: 'https://bit.ly/3cRQjNF'
  },
  {
    title: 'It Ends With Us',
    author: 'Poweisc Authorki',
    year: '2019',
    status: 'Available',
    rating: 4,
    likes: 33,
    views: 14,
    genres: 'Romance',
    labels: 'Love',
    timeAdded: 62,
    imageURL: 'https://bit.ly/30sAUAC'
  },
  {
    title: 'The Proposal',
    author: 'Jassmine Guillory',
    year: '2019',
    status: 'Available',
    rating: 4,
    likes: 33,
    views: 14,
    genres: 'Romance',
    labels: 'Love',
    timeAdded: 62,
    imageURL: 'https://bit.ly/2AVPLJm'
  },
  {
    title: 'Big Magic',
    author: 'Elizabeth Gilbert',
    year: '2014',
    status: 'available',
    rating: 4,
    likes: 234,
    views: 444,
    genres: 'motivational',
    labels: 'Self-help',
    timeAdded: 12,
    imageURL: 'https://bit.ly/3cRWHo1'
  },
  {
    title: 'Effective Python',
    author: 'Diomidis Spinellis',
    year: '2017',
    status: 'available',
    rating: 4,
    likes: 334,
    views: 944,
    genres: 'motivational',
    labels: 'Creative',
    timeAdded: 21,
    imageURL: 'https://bit.ly/3e2hN4g'
  },
  {
    title: 'Built To Last',
    author: 'Jim Collins, Jerry I. Porras',
    year: '2001',
    status: 'Borrowed Out',
    rating: 4,
    likes: 434,
    views: 144,
    genres: 'Business, Entrepreneurship',
    labels: 'Fianace',
    timeAdded: 32,
    imageURL: 'https://bit.ly/2UuKC1O'
  },
  {
    title: 'The Silent Patient',
    author: 'Alex Michealidies',
    year: '2019',
    status: 'Borrowed out',
    rating: 4,
    likes: 433,
    views: 104,
    genres: 'Scifi',
    labels: 'Meditation',
    timeAdded: 62,
    imageURL: 'https://bit.ly/3cRQjNF'
  },
  {
    title: 'The Proposal',
    author: 'Jassmine Guillory',
    year: '2019',
    status: 'Available',
    rating: 4,
    likes: 33,
    views: 14,
    genres: 'Romance',
    labels: 'Love',
    timeAdded: 62,
    imageURL: 'https://bit.ly/2AVPLJm'
  },
]